### ISSUE TITLE
TLA+ convert to PDF   exits with "latex"  not found  on MAc

### ISSUE THREAD

**Issue by akkeshavan** [tlaplus/vscode-tlaplus#266]
Error running tla2tex.TLA (exit code 1) Exception in thread "main" tla2tex.TLA2TexException: TLATeX unrecoverable error: -- Trying to run the command `latex example.tex' produced the following error Cannot run program "latex": error=2, No such file or directory. at tla2tex.Debug.ReportError(Debug.java:26) at tla2tex.ExecuteCommand.executeCommand(ExecuteCommand.java:34) at tla2tex.LaTeXOutput.RunLaTeX(LaTeXOutput.java:483) at tla2tex.TLA.runTranslation(TLA.java:246) at tla2tex.TLA.main(TLA.java:150)

Where do I set the path for Latex? I have set the path for pdflatex correctly and I can run it from the terminal and convert the .tex file to PDF.

**Comment by lemmy** [comment]
Try Settings: tlaplus.pdf.convertCommand

<img width="837" alt="Screen Shot 2022-07-30 at 10 52 59 AM" src="https://user-images.githubusercontent.com/88777/181903083-e7cf8372-cf22-4998-912b-5f44f2989cff.png">
